// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/digitalocean/droplets.proto

package droplets

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Droplet struct {
	// ID               int           `json:"id,float64,omitempty"`
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name             string        `json:"name,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Memory           int           `json:"memory,omitempty"`
	Memory int32 `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	// Vcpus            int           `json:"vcpus,omitempty"`
	Vcpus int32 `protobuf:"varint,4,opt,name=vcpus,proto3" json:"vcpus,omitempty"`
	// Disk             int           `json:"disk,omitempty"`
	Disk int32 `protobuf:"varint,5,opt,name=disk,proto3" json:"disk,omitempty"`
	// Region           *Region       `json:"region,omitempty"`
	// Image            *Image        `json:"image,omitempty"`
	// Size             *Size         `json:"size,omitempty"`
	// SizeSlug         string        `json:"size_slug,omitempty"`
	// BackupIDs        []int         `json:"backup_ids,omitempty"`
	// NextBackupWindow *BackupWindow `json:"next_backup_window,omitempty"`
	// SnapshotIDs      []int         `json:"snapshot_ids,omitempty"`
	// Features         []string      `json:"features,omitempty"`
	// Locked           bool          `json:"locked,bool,omitempty"`
	// Status           string        `json:"status,omitempty"`
	// Networks         *Networks     `json:"networks,omitempty"`
	// Created          string        `json:"created_at,omitempty"`
	Created              string   `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Droplet) Reset()         { *m = Droplet{} }
func (m *Droplet) String() string { return proto.CompactTextString(m) }
func (*Droplet) ProtoMessage()    {}
func (*Droplet) Descriptor() ([]byte, []int) {
	return fileDescriptor_0953d02212bf2f1d, []int{0}
}

func (m *Droplet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Droplet.Unmarshal(m, b)
}
func (m *Droplet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Droplet.Marshal(b, m, deterministic)
}
func (m *Droplet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Droplet.Merge(m, src)
}
func (m *Droplet) XXX_Size() int {
	return xxx_messageInfo_Droplet.Size(m)
}
func (m *Droplet) XXX_DiscardUnknown() {
	xxx_messageInfo_Droplet.DiscardUnknown(m)
}

var xxx_messageInfo_Droplet proto.InternalMessageInfo

func (m *Droplet) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Droplet) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Droplet) GetMemory() int32 {
	if m != nil {
		return m.Memory
	}
	return 0
}

func (m *Droplet) GetVcpus() int32 {
	if m != nil {
		return m.Vcpus
	}
	return 0
}

func (m *Droplet) GetDisk() int32 {
	if m != nil {
		return m.Disk
	}
	return 0
}

func (m *Droplet) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0953d02212bf2f1d, []int{1}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type ListResponse struct {
	Droplets             []*Droplet `protobuf:"bytes,1,rep,name=droplets,proto3" json:"droplets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListResponse) Reset()         { *m = ListResponse{} }
func (m *ListResponse) String() string { return proto.CompactTextString(m) }
func (*ListResponse) ProtoMessage()    {}
func (*ListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0953d02212bf2f1d, []int{2}
}

func (m *ListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResponse.Unmarshal(m, b)
}
func (m *ListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResponse.Marshal(b, m, deterministic)
}
func (m *ListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResponse.Merge(m, src)
}
func (m *ListResponse) XXX_Size() int {
	return xxx_messageInfo_ListResponse.Size(m)
}
func (m *ListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListResponse proto.InternalMessageInfo

func (m *ListResponse) GetDroplets() []*Droplet {
	if m != nil {
		return m.Droplets
	}
	return nil
}

func init() {
	proto.RegisterType((*Droplet)(nil), "Droplet")
	proto.RegisterType((*ListRequest)(nil), "ListRequest")
	proto.RegisterType((*ListResponse)(nil), "ListResponse")
}

func init() { proto.RegisterFile("proto/digitalocean/droplets.proto", fileDescriptor_0953d02212bf2f1d) }

var fileDescriptor_0953d02212bf2f1d = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x80, 0xdd, 0xfc, 0x35, 0x4e, 0x5b, 0x0f, 0x83, 0xc8, 0xe0, 0x29, 0x06, 0x85, 0x9c, 0x52,
	0xac, 0x3e, 0x82, 0x47, 0x4f, 0xfb, 0x06, 0x31, 0x3b, 0xc8, 0x62, 0x93, 0x8d, 0x99, 0xad, 0xe0,
	0x23, 0xf8, 0xd6, 0xd2, 0x4d, 0x5a, 0x72, 0x9b, 0xef, 0x1b, 0xf8, 0x18, 0x06, 0x1e, 0x86, 0xd1,
	0x79, 0xb7, 0x33, 0xf6, 0xd3, 0xfa, 0xe6, 0xe0, 0x5a, 0x6e, 0xfa, 0x9d, 0x19, 0xdd, 0x70, 0x60,
	0x2f, 0x75, 0xd8, 0x95, 0x7f, 0x0a, 0x56, 0x6f, 0x93, 0xc2, 0x1b, 0x88, 0xac, 0x21, 0x55, 0xa8,
	0x2a, 0xd6, 0x91, 0x35, 0x88, 0x90, 0xf4, 0x4d, 0xc7, 0x14, 0x15, 0xaa, 0xba, 0xd6, 0x61, 0xc6,
	0x3b, 0xc8, 0x3a, 0xee, 0xdc, 0xf8, 0x4b, 0x71, 0xa1, 0xaa, 0x54, 0xcf, 0x84, 0xb7, 0x90, 0xfe,
	0xb4, 0xc3, 0x51, 0x28, 0x09, 0x7a, 0x82, 0x53, 0xc1, 0x58, 0xf9, 0xa2, 0x34, 0xc8, 0x30, 0x23,
	0xc1, 0xaa, 0x1d, 0xb9, 0xf1, 0x6c, 0x28, 0x0b, 0xe1, 0x33, 0x96, 0x5b, 0x58, 0xbf, 0x5b, 0xf1,
	0x9a, 0xbf, 0x8f, 0x2c, 0xbe, 0x7c, 0x85, 0xcd, 0x84, 0x32, 0xb8, 0x5e, 0x18, 0x1f, 0x21, 0x3f,
	0x1f, 0x4f, 0xaa, 0x88, 0xab, 0xf5, 0x3e, 0xaf, 0xe7, 0xd3, 0xf5, 0x65, 0xb3, 0x7f, 0x86, 0x7c,
	0x96, 0x82, 0x4f, 0x90, 0x9c, 0x0a, 0xb8, 0xa9, 0x17, 0xdd, 0xfb, 0x6d, 0xbd, 0xcc, 0x96, 0x57,
	0x1f, 0x59, 0x78, 0xc5, 0xcb, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x19, 0x72, 0xf7, 0x3a, 0x2f,
	0x01, 0x00, 0x00,
}
